recipes:
  global:
    - ruby_build::default
    - rbenv::user
attributes:
  ruby_build:
    upgrade: true
  rbenv:
    create_profiled: false
    user_installs:
      -
        user: <%= ENV['USER'] %>
        global: 2.1.5
        root_path: /Users/<%= ENV['USER'] %>/.rbenv
    user_rubies:
      - 2.1.5
    user_gems:
      2.1.5:
        -
          name: bundler
        -
          name: rails
        -
          name: thegarage-gitx
    user_plugins:
      -
        name: rbenv-binstubs
        git_url: https://github.com/ianheggie/rbenv-binstubs.git
        git_ref: v1.4
      -
        name: rbenv-bundler-ruby-version
        git_url: https://github.com/aripollak/rbenv-bundler-ruby-version.git
        git_ref: v0.2
      -
        name: rbenv-gem-rehash
        git_url: https://github.com/sstephenson/rbenv-gem-rehash.git
        git_ref: v1.0.0
  homebrew:
    formulas:
      - git
      - pkg-config
      - cmake
      - libpqxx
      - phantomjs
      - heroku
      - nodejs
      - ansible
      - lastpass-cli
      - postgresql
      - vim
    casks:
      - virtualbox
      - vagrant
      - mou
      - github
